FROM php:8.2-apache

# Enable mod_rewrite AND allow .htaccess to use it
RUN a2enmod rewrite && \
  sed -i 's/AllowOverride None/AllowOverride All/g' /etc/apache2/apache2.conf

COPY . /var/www/html/

EXPOSE 80